[project]
name = "pynq_uart"
version = "0.1.0"

[build]
sources = ["src"]
target = { type = "directory", path = "target" }
clock_type = "posedge"
reset_type = "sync_high"
omit_project_prefix = true
implicit_parameter_types = ["string"]
expand_inside_operation = true
sourcemap_target = { type = "directory", path = "target/sourcemap" }
